# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8089
  servlet:
    # 应用的访问路径
    context-path: /
    session:
      tracking-modes: cookie
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    max-http-form-post-size: 10MB
  max-http-header-size: 4048576

# 微信配置
wx:
  app-id: wx7b013dd72070f493
  mch-id: 1699445935
  mch-serial-no: #############################
  app-secret: #######################
  api-key: ######################
  notify-url: https://fjk.iirl.top/stu-api/wechat/pay/payNotify
#  key-path: src\main\resources\wechatpay\pub_key.pem
#  private-key-path: src\main\resources\wechatpay\apiclient_key.pem
  key-path: /data/cert/pub_key.pem
  private-key-path: /data/cert/apiclient_key.pem

  public-key-id: PUB_KEY_ID_0116994459352024111900397200000327

# Spring配置
spring:
  datasource:
    url: jdbc:mysql://###########/uni-retrieval?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
#    password: CMjy8888
    password：12356789

# 日志配置
logging:
  level:
    root: ERROR
    com.retrieval: debug
    org.springframework: warn

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 120

# jwt
jwt:
  header: Authorization # 令牌自定义标识
  secret: w-oasisljiund  # 令牌密钥
  expiration: 630720000 #token
  tokenHead: xgxt-api
  exceptUrl: /user/signup
  tokenParam: token
mybatis-plus:
  type-enums-package: com.demo.mybatisplus.constant #配置枚举 支持通配符 * 或者 ; 分割
  typeAliasesPackage: com.qilu.xuegong.**.domain
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler # 自mybatis3.1.0开始，如果你无需使用原生枚举，可配置默认枚举来省略扫描通用枚举配置 默认枚举配置
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: 127.0.0.1:8080

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: 1
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
